#!/bin/bash

set -e

sudo aptitude update -y
sudo aptitude upgrade -y
sudo aptitude -y -q install linux-headers-$(uname -r) build-essential dkms nfs-common

#sudo groupadd -r admin
#sudo usermod -a -G admin vagrant
#cp /etc/sudoers /etc/sudoers.orig
#sudo sed -i -e '/Defaults\s\+env_reset/a Defaults\texempt_group=admin' /etc/sudoers
#sudo sed -i -e 's/%admin ALL=(ALL) ALL/%admin ALL=NOPASSWD:ALL/g' /etc/sudoers

sudo echo 'vagrant ALL=(ALL) NOPASSWD:ALL' >/etc/sudoers.d/99_vagrant
sudo chmod 440 /etc/sudoers.d/99_vagrant
sudo echo "Defaults !requiretty" >>/etc/sudoers

mkdir ~/.ssh
chmod 700 ~/.ssh
wget --no-check-certificate 'https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub' -O ~/.ssh/authorized_keys2
chmod 600 ~/.ssh/authorized_keys2
chown -R vagrant ~/.ssh

sudo apt-get -y --purge remove linux-headers-$(uname -r) build-essential
sudo apt-get -y --purge autoremove
sudo apt-get -y purge $(dpkg --list |grep '^rc' |awk '{print $2}')
sudo apt-get -y purge $(dpkg --list |egrep 'linux-image-[0-9]' |awk '{print $3,$2}' |sort -nr |tail -n +2 |grep -v $(uname -r) |awk '{ print $2}')
sudo apt-get -y clean

sync
