#!/bin/bash

set -e

# Install VBoxGuestAdditions
[ -f /etc/init.d/virtualbox-guest-utils ] && /etc/init.d/virtualbox-guest-utils stop || true
sleep 5
[ $(lsmod|grep -q vboxguest) ] && rmmod -f vboxguest || true

aptitude -y -q purge virtualbox-ose-guest-x11 virtualbox-ose-guest-dkms virtualbox-ose-guest-utils virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
aptitude -y -q install --without-recommends linux-headers-$(uname -r) build-essential nfs-common dkms
aptitude -y -q install --without-recommends libdbus-1-3 module-assistant

VBOX_VERSION=$(cat /home/vagrant/.vbox_version)

mount -o loop VBoxGuestAdditions.iso /mnt
yes|REMOVE_INSTALLATION_DIR=0 /mnt/VBoxLinuxAdditions.run --nox11
umount /mnt
rm -f VBoxGuestAdditions.iso

[ -e /usr/lib/VBoxGuestAdditions ] || ln -s /opt/VBoxGuestAdditions-$VBOX_VERSION/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions

# Remove old packages
aptitude -y purge $(dpkg --list |grep '^rc' |awk '{print $2}')
aptitude -y purge $(dpkg --list |egrep 'linux-image-[0-9]'|grep -v $(uname -r)|awk '{print $2}')

# Remove APT cache
aptitude -y autoclean
aptitude -y clean

# Cleanup dhcp leases
rm -f /var/lib/dhcp/*

# Cleanup tmp
rm -rf /tmp/*

# Cleanup log files
find /var/log -type f | while read f; do echo -ne '' > $f; done;

# Remove APT files and old debconf files
find /var/lib/apt* -type f | xargs rm -f
find /var/cache/debconf -type f -name '*-old' | xargs rm -f

# Remove unused locales
find /usr/share/locale -maxdepth 1 -mindepth 1 -not -name 'en*' -not -name 'fr*' | xargs rm -rf

# Remove bash history
unset HISTFILE
[ -f /root/.bash_history ] && rm /root/.bash_history
[ -f /home/vagrant/.bash_history ] && rm /home/vagrant/.bash_history

# Zero free space to aid VM compression
dd if=/dev/zero of=/EMPTY bs=1M || true
rm -f /EMPTY
